title: W3C/OGC Joint Workshop on Maps for the Web
description: >-
  Monday June 15th to Wednesday June 17th 2020, Montreal, Canada
url: "https://maps4html.github.io/Maps4HTML-Workshop-2020"

theme: null

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
